### ISSUE TITLE
error happens when installing the package

### ISSUE THREAD

**Issue by Spatial-R** [sbfnk/RBi.helpers#1]
When i try to install the **RBi.helpers** package using the codes:    
devtools::install_github("sbfnk/RBi.helpers")

Error : object ‘remove_lines’ is not exported by 'namespace:rbi'
ERROR: lazy loading failed for package ‘rbi.helpers’.

How can i fixed this problem?

**Comment by sbfnk** [comment]
Thanks @Spatial-R for the report. This should not happen with the latest version (0.7) of `rbi`. Please update `rbi` using `install.packages('rbi')` and re-open if the problem persists.
