### ISSUE TITLE
Adapting the proposal for models that have some parameters with no output

### ISSUE THREAD

**Issue by seabbs** [sbfnk/RBi.helpers#3]
Hi Seb, 

Sorry for the multiple issues in a day - this is again a great package :). It looks like you may have caught this with your latest commits but not quite sure so reporting just in case.

Essentially the issue is that when adapting the proposal parameters that have no output are needed in order to run the model without sampling. Happy to add a reproducible example if useful. For my use case, I solved with the following (very crude function) that adds all parameters into the model. After adapting the proposal I then revert to the old model. 

```
#' Adapt LibBi model with all Variables in Output
#'
#' @description Some \code{rbi.helper} functions require all variables to have outputs. This function modifies a LibBi model 
#' so that this is the case.
#' @param model A LibBi model, loaded using \code{bi_model}.
#'
#' @return A LibBi model.
#' @export
#'
#' @importFrom rbi replace_all
#' @examples
#' library(rbi)
#' 
#' model <- system.file(package="rbi", "SIR.bi") # get full file name from package
#' model <- bi_model(model) # load model
#' model <- replace_all(model, "noise n_recovery", "noise n_recovery\\(has_output = 0\\)")
#' 
#' model
#' 
#' everything_from_model(model)
everything_from_model <- function(model) {
  
 model <- replace_all(model, "\\(has_output = 0, has_input = 0\\)", "")
 model <- replace_all(model, "\\(has_input = 0, has_output = 0\\)", "")
 model <- replace_all(model, "\\(has_output = 0\\)", "")
 
 return(model)
}
```

Thanks, 

Sam

**Comment by sbfnk** [comment]
The commit referenced above should this - please re-open if it doesn't. It requires a recent development version of `rbi`.
