### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by seabbs** [sbfnk/RBi.helpers#5]
Hi Seb, 

Thanks again for this package - started using it for the final stage of my thesis :smile:

I noticed that you recently dropped the plotting function from your development version. 

I see from the commits that this was done as plotting can be done quite easily by the user. I just wanted to point out that when first using `rbi` + `rbi.helpers` the plotting functionality was very helpful.

I have since rolled my own but was still using the integrated plotting on occasion for quick diagnostics.

Any chance of this being added back in? Alternatively if you feel like it should go in a seperate visualisation package this is something I would be happy to work on. 

Thanks, 

Sam

**Comment by sbfnk** [comment]
Sam,

Sorry for not responding to this at the time - seems like I didn't have notifications for issues set up.

It's probably too late to be helpful, but my thinking was that this is much better served by existing packages - plotting trajectories is simple enough to do as in the `rbi` vignette. For MCMC diagnostics I use the `ggmcmc` package, e.g.
```
library('coda')
traces <- mcmc(get_traces(bi))
s <- ggs(traces)
ggmcmc(ggs)
```

I'll close this for now - please feel free to re-open if you think it's worth discussing further.

Seb.
