### ISSUE TITLE
bi_read and proposal adaption

### ISSUE THREAD

**Issue by seabbs** [sbfnk/RBi.helpers#6]
Hi Seb, 

Sorry for the multiple issues. 

Using the newly updated `adapt_proposal` function I am seeing an error when trying to read in the input file (i.e with `rbi::bi_read(model, file = "input")`).

I am having trouble coming up with a reproducible example as the SIR model used in the vignette works fine. 

During adaption, I am seeing an `ncvar: warning` which looks like there is a problem with the new proposal variables. My only potential thought is that it may be because I am using vectors and matrices. 

When I go to read in the input file I see the following error.

```
Error in factor(mav[[col]], labels = dims[[dim_col]]) : 
  invalid 'labels'; length 120 should be 1 or 92
```
Tried localising in the code but struggling to debug. I will keep trying to produce an example of this in the wild.

**Comment by sbfnk** [comment]
Closing as it may have been fixed by subsequent updates. Please re-open with a reproducible example if this problem persists.
